### ISSUE TITLE
Documentation incomplete

### ISSUE THREAD

**Issue by MauricePonte** [JakobSig/HSI2RGB#3]
Hi Jakob, 

I'm trying to implement your function to read our own made HSI images. But I'm having trouble understanding what the wY parameter of the HSI2RGB function should be. Is this something that must be calculated? If so in what way?

Thank you in advance!

**Comment by JakobSig** [comment]
Hello Maurice

The wY parameters are the wavelengths of the spectral bands. The size of wY
is the number of spectral bands and each value in wY dictates the
wavelength of a spectral band,

For example, of you have AVIRIS data, the wY file should hold values
between 400 to 2500, see https://aviris.jpl.nasa.gov/aviris/index.html

In the washington_hsi.mat file, the wl vector holds the wavelengths.
Look at the demo.m file, it first loads the  washington_hsi file and then
calls the  HSI2RGB method.

Regards,
   Jakob S.
